<form action="https://www.example.com/payment/success/" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    
    data-key="rzp_test_VqIdkt0aIfImsJ" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    
    //ithe_khali-je-apan-amount-taknar-te-post-honar
    <?php $totalPrice=((int)$_POST['$totalPrice'])*100;?>
    data-amount="<?php echo $totalPrice; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    //data-amount="<?php echo $_POST['$totalPrice']*100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    
    //data-order_id="order_CgmcjRh9ti2lP7"
    data-id="<?php echo 'TechAliens'.rand(10,100).'END';?> " // Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"

    //name_that_come_on_heading
    //data-name="Acme_Corp"
    data-name="TechAliens"

    //descripttion_of_company_or_website
    data-description="Shop for mobile and accessories!"

    //here-only-scure-website-logo-can-be-added
    data-image="https://example.gcom/your_logo.jpg"

    //this-is-the-users-name
    data-prefill.name="<?php echo $_POST['name'] ?>"
    data-prefill.email="<?php echo $_POST['email'] ?>"
    data-prefill.contact="<?php echo $_POST['phone'] ?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>

<style>
    .rayzorpay-payment-button{display:none}
</style>
<script>
    $(document).click(function (e) { 
        e.preventDefault();
        $('.razorpay-payment-button').click();
    });

</script>